name: Godbolt C/C++ CI

on:
  push:
    branches:
      - master

jobs:
  godbolt:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build preprocessed file
      run: cpp include/unconstexpr.hpp | grep -v '^#' > output.cpp && cat tests/unconstexpr.cpp  | grep -v 'unconstexpr.hpp' >> output.cpp

    - name: test latest gcc
      run: curl 'https://godbolt.org/api/compiler/gsnapshot/compile?options=-std=c%2b%2b2a' --data-binary "$(cat output.cpp)"
    - name: test latest clang
      run: curl 'https://godbolt.org/api/compiler/clang_trunk/compile?options=-std=c%2b%2b2a' --data-binary "$(cat output.cpp)"

    - name: test gcc 9.1
      run: curl 'https://godbolt.org/api/compiler/g91/compile?options=-std=c%2b%2b2a' --data-binary "$(cat output.cpp)"

    - name: test clang 9.0
      run: curl 'https://godbolt.org/api/compiler/clang900/compile?options=-std=c%2b%2b2a' --data-binary "$(cat output.cpp)"

  header:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2-beta
      with:
        ref: godbolt
    - name: godbolt header
      run: |
        git fetch refs/remotes/origin/
        git reset --hard refs/remotes/origin/master
        cpp include/unconstexpr.hpp > unconstexpr_godbolt.hpp

        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git add unconstexpr_godbolt.hpp
        git commit -m "Update godbolt header"
        git push -f

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: godbolt
        github_token: ${{ secrets.GITHUB_TOKEN }}
