name: Godbolt C/C++ CI

on:
  push:
    branches:
      - master
  schedule:
    # Every sunday
    - cron:  '0 0 * * 0'

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build preprocessed header
      run: cpp -C include/unconstexpr/unconstexpr.hpp > unconstexpr.hpp
    - name: build preprocessed file
      run:  grep -v '^#' unconstexpr.hpp > output.cpp && grep -v 'unconstexpr.hpp' tests/unconstexpr.cpp >> output.cpp
    - uses: actions/upload-artifact@v1
      with:
          name: output
          path: unconstexpr.hpp
    - uses: actions/upload-artifact@v1
      with:
          name: output
          path: output.cpp


  godbolt_test:
    runs-on: ubuntu-latest
    needs: [preprocess]
    strategy:
      matrix:
        compiler: ['gcc trunk', 'clang trunk', 'gcc 9.1', 'clang 9.0']
        include:
          - compiler: 'gcc trunk'
            id: 'gsnapshot'
          - compiler: 'clang trunk'
            id: 'clang_trunk'
          - compiler: 'gcc 9.1'
            id: 'g91'
          - compiler: 'clang 9.0' 
            id: 'clang900'

    steps:
    - uses: actions/download-artifact@v1
      with:
          name: output
    - name: test ${{ matrix.compiler }}
      run: curl 'https://godbolt.org/api/compiler/${{ matrix.id }}/compile?options=-std=c%2b%2b2a%20-O3' --data-binary "$(cat output/output.cpp)"

  header:
    runs-on: ubuntu-latest
    needs: [preprocess]
    
    steps:
    - uses: actions/checkout@v1
      with:
        ref: godbolt
    - uses: actions/download-artifact@v1
      with:
          name: output
    - name: godbolt header
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        mv output/unconstexpr.hpp godbolt.hpp
        git add godbolt.hpp
        git commit -m "Update godbolt header" || exit 0

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: godbolt
        github_token: ${{ secrets.GITHUB_TOKEN }}
